const CONSTANTES = {
    REGISTRO: 'REGISTRO',
    LOGIN: 'LOGIN',
    ESTABLECER_SESION:'ESTABLECER_SESION',
    CERRAR_SESION:'CERRAR_SESION',
    LIMPIAR_IMAGEN_SIGNUP:'LIMPIAR_IMAGEN_SIGNUP',
    CARGAR_IMAGEN_SIGNUP:'CARGAR_IMAGEN_SIGNUP',
    CLOUDINARY_NAME:'https://api.cloudinary.com/v1_1/dzxmrgbiy/image/upload',
    CLOUDINARY_PRESET:'qtp56zha',
    CARGAR_IMAGEN_PUBLICACION:'CARGAR_IMAGEN_PUBLICACION',
    LIMPIAR_IMAGEN_PUBLICACION:'LIMPIAR_IMAGEN_PUBLICACION',
    SUBIR_PUBLICACION:'SUBIR_PUBLICACION',
    DESCARGAR_PUBLICACIONES:'DESCARGAR_PUBLICACIONES',
    AGREGAR_PUBLICACIONES_STORE:'AGREGAR_PUBLICACIONES_STORE',
};
export default CONSTANTES;